services:
  backend:
    build: ./backend
    ports:
      - "8550:8000"
    volumes:
      - ./backend_data:/app/data
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  frontend:
    build: ./frontend
    ports:
      - "3550:80"
    depends_on:
      - backend
